url: /editor/action?a=settingssave
ajax: true
submit_value: Save
id: frm_element_settings
items:
  settings:
    type: text
    lable: Settings
    default: 
    container_classzzz: row
    style: 'min-height: 300px'
  stay:
    type: checkbox
    lable: Do not close this window
  file:
    type: hidden
    lable: 'File'
    mandatory: true
    default: ''
    container_style: 'display:zzznone;'
  key:
    type: hidden
    lable: 'Key'
    mandatory: true
    default: ''
    container_style: 'display:zzznone;'
#  action:
#    type: hidden
#    lable: action
#    mandatory: true
#    default: 'create'
#success_redirect: /page/home
#buttons:
#  -
#    type: a
#    innerHTML: Delete
#    attribute:
#      href: '#'
#      onclick: "$.get('/editor/action?a=attribute_delete&file='+encodeURIComponent(document.getElementById('frm_element_attribute_file').value)+'&key='+encodeURIComponent(document.getElementById('frm_element_attribute_key').value)+'&attribute='+encodeURIComponent(document.getElementById('frm_element_attribute_attribute').value)+'', function(data){PluginWfCallbackjson.call( data );})"
#      classzzz: 'btn btn-default'
